.gitignore:
    paths:
        - "/test/integration/**/.librarian"
        - "/test/integration/**/.tmp"
        - ".kitchen"
        - ".vscode"
Gemfile:
    required:
        ":development":
            - gem: "kitchen-docker"
              version: "2.9.0"
            - gem: "kitchen-puppet"
              version: "3.5.1"
            - gem: "serverspec"
              version: "2.41.5"
            - gem: "test-kitchen"
              version: "2.3.4"
            - gem: "github_changelog_generator"
              version: "1.15.0"
Rakefile:
    changelog_user: "dodevops"
    changelog_project: "https://github.com/dodevops/puppet-ocsinventoryagent"
    requires:
        - "kitchen/rake_tasks"
    extras:
        - "Kitchen::RakeTasks.new"
        - |
            task :integration_test do
              [:metadata_lint, :lint, :validate, :spec].each do |test|
                Rake::Task[test].invoke
              end
              Rake::Task['kitchen:all'].invoke
            end
.travis.yml:
    includes:
        - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=integration_test
          rvm: 2.5.3
          stage: spec
          script: 'travis_wait 40 bundle exec rake $CHECK'
    user: "dodevops"
    secure: "A1BDLu3QBdPgST473spzQ0d5YM1lOs3rOTjO9Civ8MZrzk/3tnWpLKYMxd9jY/D1eAcc9P1CwgBiW3/I8C+PK0NZcg8pWAk8bN65d6kKlAOu1P2ZOB9fFK79ZCxeYGGx1PV7fhAjLijkDqs8PjEhp65BnKyK9jM9x57QxI0URQ/EBzyBx1ownRkiDhNKTE8b4PITNegbweNEbMldyrg1PdPdr0+E95ELXewFBHeKlFMmwWLjaBgdSCr51bJ2zdb2V/7a7iAOTuUhG/mQxFOUsEf4JP/Jvhu2doz/A7l16LtN9idqoef3JECvuveB1vUQLuu3Utc/ouXjkcKzcRPpNpfQsmc1U8ohWvXtR2u0oyfHMdY4CWUdG7U4kngwy2B8ZjHV0LWTLbPX/23ZkHPY+Sm8FdyH7r4A0X04DazpkdSQ2vfMXAYdYRBvV0Jb8rMMbDDsm/Z9vkiZqZKWDfi+lK+wBgqqzBoS792N+ThdT7TMxBMu/BnKjjua73UbU7ITllAV78F301HOPNDLS015wEcZmakQf2k6K5anlqooBDDrVmePmOoinAhTaXth8vZ49XDdPFOJ/ktzgDdkBHYd6VbTk+A4hj/wW4ySvaJZlgX7TCj194l7EUylktj9zdz7UEvhRkOGcm/YuHvYpW0ZKMJilfC1md8uEB+x+iiKs/0="
